export const ROUTES = {
   DASHBOARD_HOME: 'dashboardHome',
   ONBOARDING: 'onBoarding',
   CUSTOMERSIGNUP: 'CustomerSignup',
   CUSTOMERLOGIN: 'CustomerLogin',
   CONTACTUS: 'ContactUs',
   HOME: 'Home',
   REQUESTS: 'Requests',
   PACKAGE: 'Package',
   NOTIFICATIONS: 'Notifications',
   HISTORY: 'History',
   PENDING: 'Pending',
   DASHBOARD: 'Dashboard',
   MESSAGES: 'Messages',
   CHAT_LIST: 'Chat List',
   CHAT: 'Chat',
   ACTION_TEAM: 'ActionTeam',
   PROFILE: 'Profile',
   CHATBOT: 'ChatBot',
   PACKAGE_DETAILS: 'Package Details',
   BUSINESS_ADDRESS: 'Business Address',
};
