export const CLAUSES = {
   SIGNUP: 'Signup',
   LOGIN: 'Login',
   SIGN_IN: 'Sign In',
   ACTION_TEAM_LOGIN: 'Action Team Login',
   WELCOME_MESSAGE: 'Discover Endless Possibilities with Quick Fix',
   DESCRIPTION: 'You are just a click away to get your maintenance work done by our expert team',
   HAVE_ANY_QUESTIONS: 'Have any Questions? ',
   NOT_HAVE_AN_ACCOUNT: 'Not have an account? ',
   SIGN_UP_NOW: 'Sign Up Now',
   CONTACT_US: 'Contact us',
   ENTER_YOUR_EMAIL: 'Enter Your Email',
   ENTER_YOUR_PASSWORD_HERE: 'Enter Your Password Here',
   INVALID_EMAIL: 'Invalid email',
   REQUIRED: 'Required',
   TOO_SHORT: 'too short',
   TOO_LARGE: 'too large',
   TOO_YOUNG: 'too young',
   TOO_OLD: 'too old',
   TOO_LESS: 'too less',
   TOO_MUCH: 'too much',
   ONLY_NUMBERS: 'The field must contain only numbers',
   THIS_FIELD_MUST_CONTAIN_ONLY_NUMBERS: 'This field must contain only numbers',
   ENTER_YOUR_BUSINESS_NAME: 'Enter Your Business Name',
   ENTER_YOUR_BUSINESS_ADDRESS: 'Enter Your Business Address',
   ENTER_YOUR_CONTACT_NAME: 'Enter Your Contact Name',
   ENTER_YOUR_CONTACT_NUMBER: 'Enter Your Contact Number',
   ENTER_YOUR_PREFERRED_USER_ID: 'Enter Your Preferred User ID',
   ADD_YOUR_ADDRESS: 'Add Business Address',
   NEW_CUSTOMER_SIGN_UP: 'New Customer Sign Up',
   RAISE_SERVICE_REQUEST: 'Raise Service Request',
   HEATING_AND_COOLING_SYSTEM: 'Heating and Cooling System',
   ANY_OTHER_SERVICE: 'Any Other Service',
   OPTED_PACKAGE: 'Opted Package :',
   PAY_AS_YOU_GO: 'Pay as You Go',
   TOTAL_REQUESTS: 'Total Requests',
   USED_REQUESTS: 'Used Requests',
   REMAINING_REQUESTS: 'Remaining Requests',
   REQUEST_COST: 'Request Cost',
   BUSINESS_NAME: 'Business Name',
   TERMS_AND_CONDITIONS: 'Terms & Conditions',
   CONTACT_NUMBER: 'Contact Number',
   PROBLEM_DESCRIPTION: 'Problem Description',
   DESCRIBE_YOUR_PROBLEM: 'Describe Your Problem',
   SELECT_A_TIME_SLOT: 'Select a Time Slot',
   YOUR_REQUEST_IS_FOR_THIS_DATE: 'Your request is for this date',
   SUBMIT_REQUEST: 'Submit Request',
   REQUEST_USAGE: 'Request Usage',
   LOADING_SUBSCRIPTION_DETAILS: 'Loading subscription details',
   ERROR_FETCHING_USER_DETAILS: 'Error fetching user details.',
};

export const WORDS = {
   OR: 'OR',
   BUTTON: 'Button',
   SIGN_IN: 'Sign In',
   SIGN_UP: 'Sign Up',
   PLUMBERING: 'Plumbering',
   ELECTRICAL: 'Electrical',
   DRAINAGE: 'Drainage',
   SUBMIT: 'Submit',
   EMAIL: 'Email',
   PROFILE: 'Profile',
   REMAINING: 'Remaining',
   STATUS: 'Status',
   PREMIUM: 'Premium',
   USED: 'Used',
   LOGOUT: 'Logout',
   WELCOME: 'Welcome',
};
